
DROP SEQUENCE supplier_sequence;
CREATE SEQUENCE supplier_sequence INCREMENT BY 1 START WITH 77;

INSERT INTO supplier (id, active, name) VALUES (	1	,1,'INFOSYS TECHNOLOGIES LTD');
INSERT INTO supplier (id, active, name) VALUES (	2	,1,'TECH MAHINDRA LTD');
INSERT INTO supplier (id, active, name) VALUES (	3	,1,'EMC COMPUTER SYSTEMS (U.K.) LTD');
INSERT INTO supplier (id, active, name) VALUES (	4	,1,'COMPUTER ASSOCIATES PLC');
INSERT INTO supplier (id, active, name) VALUES (	5	,1,'VIRTUSA UK LTD');
INSERT INTO supplier (id, active, name) VALUES (	6	,1,'TATA CONSULTANCY SERVICES LTD');
INSERT INTO supplier (id, active, name) VALUES (	7	,1,'CSS EUROPE LTD');
INSERT INTO supplier (id, active, name) VALUES (	8	,1,'HAYS SPECIALIST RECRUITMENT LTD');
INSERT INTO supplier (id, active, name) VALUES (	9	,1,'STERIA LTD');
INSERT INTO supplier (id, active, name) VALUES (	10	,1,'DIGITAL FUEL TECHNOLOGIES LTD');
INSERT INTO supplier (id, active, name) VALUES (	11	,1,'HEWLETT PACKARD LTD');
INSERT INTO supplier (id, active, name) VALUES (	12	,1,'ACCENTURE (U K) LTD');
INSERT INTO supplier (id, active, name) VALUES (	13	,1,'HEWLETT-PACKARD GMBH');
INSERT INTO supplier (id, active, name) VALUES (	14	,1,'KYAK SYSTEMS B V');
INSERT INTO supplier (id, active, name) VALUES (	15	,1,'ACADGRAPH GMBH');
INSERT INTO supplier (id, active, name) VALUES (	16	,1,'ORACLE DEUTSCHLAND GMBH');
INSERT INTO supplier (id, active, name) VALUES (	17	,1,'DETICA LTD');
INSERT INTO supplier (id, active, name) VALUES (	18	,1,'INSIGHT TECHNOLOGY SOLUTIONS GMBH');
INSERT INTO supplier (id, active, name) VALUES (	19	,1,'BARRASTONE COMPUTING LTD');
INSERT INTO supplier (id, active, name) VALUES (	20	,1,'SINGULARITY LTD');
INSERT INTO supplier (id, active, name) VALUES (	21	,1,'NETMANIA I.T. LTD');
INSERT INTO supplier (id, active, name) VALUES (	22	,1,'SPRING TECHNOLOGY STAFFING SERVICES LTD');
INSERT INTO supplier (id, active, name) VALUES (	23	,1,'ASIDUA LTD');
INSERT INTO supplier (id, active, name) VALUES (	24	,1,'COMPUBITS SUPPORT LTD');
INSERT INTO supplier (id, active, name) VALUES (	25	,1,'HCL TECHNOLOGIES LIMITED');
INSERT INTO supplier (id, active, name) VALUES (	26	,1,'SUBEX (UK) LTD');
INSERT INTO supplier (id, active, name) VALUES (	27	,1,'LOGICA UK LTD');
INSERT INTO supplier (id, active, name) VALUES (	28	,1,'SIEMENS IT SOLUTIONS AND SERVICES LTD');
INSERT INTO supplier (id, active, name) VALUES (	29	,1,'AMDOCS SOFTWARE SYSTEMS LTD');
INSERT INTO supplier (id, active, name) VALUES (	30	,1,'TRANSPUTEC FZ LLC');
INSERT INTO supplier (id, active, name) VALUES (	31	,1,'DELOITTE M C S LTD');
INSERT INTO supplier (id, active, name) VALUES (	32	,1,'ORACLE CORPORATION U K LTD');
INSERT INTO supplier (id, active, name) VALUES (	33	,1,'MPHASIS CONSULTING LTD');
INSERT INTO supplier (id, active, name) VALUES (	34	,1,'SOURCESENSE LTD');
INSERT INTO supplier (id, active, name) VALUES (	35	,1,'I-ASSOCIATES (UK) LTD');
INSERT INTO supplier (id, active, name) VALUES (	36	,1,'COGNIZANT TECHNOLOGY SOLUTIONS LTD');
INSERT INTO supplier (id, active, name) VALUES (	37	,1,'ALCATEL-LUCENT TELECOM LTD');
INSERT INTO supplier (id, active, name) VALUES (	38	,1,'UI CENTRIC LTD');
INSERT INTO supplier (id, active, name) VALUES (	39	,1,'RIGHTNOW TECHNOLOGIES (UK) LTD');
INSERT INTO supplier (id, active, name) VALUES (	40	,1,'COMPUTACENTER (U K) LTD');
INSERT INTO supplier (id, active, name) VALUES (	41	,1,'FUJITSU SERVICES LTD');
INSERT INTO supplier (id, active, name) VALUES (	42	,1,'TALLIS ASSOCIATES LLP');
INSERT INTO supplier (id, active, name) VALUES (	43	,1,'UNITED TECHNOLOGISTS EUROPE LTD');
INSERT INTO supplier (id, active, name) VALUES (	44	,1,'SOFTWARE MEASUREMENT SERVICES LTD');
INSERT INTO supplier (id, active, name) VALUES (	45	,1,'IMPLEMENT.COM CORPORATION');
INSERT INTO supplier (id, active, name) VALUES (	46	,1,'CONVERGYS EMEA LTD');
INSERT INTO supplier (id, active, name) VALUES (	47	,1,'SUN MICROSYSTEMS LTD');
INSERT INTO supplier (id, active, name) VALUES (	48	,1,'BT ENGAGE IT LTD');
INSERT INTO supplier (id, active, name) VALUES (	49	,1,'UNISYS LTD');
INSERT INTO supplier (id, active, name) VALUES (	50	,1,'HEWLETT-PACKARD BELGIUM SPRL');
INSERT INTO supplier (id, active, name) VALUES (	51	,1,'SUN MICROSYSTEMS');
INSERT INTO supplier (id, active, name) VALUES (	52	,1,'TRAC NV');
INSERT INTO supplier (id, active, name) VALUES (	53	,1,'ALL PROFESSIONAL SERVICES NV');
INSERT INTO supplier (id, active, name) VALUES (	54	,1,'CVIDYA NETWORKS UK LTD');
INSERT INTO supplier (id, active, name) VALUES (	55	,1,'WESTHILL GROUP LTD');
INSERT INTO supplier (id, active, name) VALUES (	56	,1,'VEBNET LTD');
INSERT INTO supplier (id, active, name) VALUES (	57	,1,'SYMPHONO LLC');
INSERT INTO supplier (id, active, name) VALUES (	58	,1,'GLUE SOFTWARE ENGINEERING AG');
INSERT INTO supplier (id, active, name) VALUES (	59	,1,'MASSIVE INTERACTIVE PTY LTD');
INSERT INTO supplier (id, active, name) VALUES (	60	,1,'INFINITIS LTD');
INSERT INTO supplier (id, active, name) VALUES (	61	,1,'CONSULTING INFORMATICO DE CANTABRIA S.L.');
INSERT INTO supplier (id, active, name) VALUES (	62	,1,'K P M G LLP');
INSERT INTO supplier (id, active, name) VALUES (	63	,1,'HOLONOMIX LTD');
INSERT INTO supplier (id, active, name) VALUES (	64	,1,'THEPLATFORM FOR MEDIA, INC');
INSERT INTO supplier (id, active, name) VALUES (	65	,1,'SUN MICROSYSTEMS COMPUTERS');
INSERT INTO supplier (id, active, name) VALUES (	66	,1,'INMAC WSTORE');
INSERT INTO supplier (id, active, name) VALUES (	67	,1,'ISOFTSTONE INFORMATION SERVICE CORPORATION');
INSERT INTO supplier (id, active, name) VALUES (	68	,1,'EUROSIS LTD');
INSERT INTO supplier (id, active, name) VALUES (	69	,1,'Erlang Training and Consulting Ltd');
INSERT INTO supplier (id, active, name) VALUES (	70	,1,'Enterprise jBilling Software LTD');
INSERT INTO supplier (id, active, name) VALUES (	71	,1,'GOSU AS');
INSERT INTO supplier (id, active, name) VALUES (	72	,1,'VERIZON UK LTD');
INSERT INTO supplier (id, active, name) VALUES (	73	,1,'AZDIO LTD');
INSERT INTO supplier (id, active, name) VALUES (	74	,1,'ACUTEST LTD');
INSERT INTO supplier (id, active, name) VALUES (	75	,1,'OMNINET');
INSERT INTO supplier (id, active, name) VALUES (	76	,1,'CLIENT COMPUTING GERMANY GMBH');
